# Copyright (c) Kasefuchs
# SPDX-License-Identifier: MPL-2.0

---
version: 3

tasks:
  add-copyright-headers:
    cmd: go run github.com/hashicorp/copywrite headers

  buf-generate:
    cmd: go run github.com/bufbuild/buf/cmd/buf generate

  buf-lint:
    cmd: go run github.com/bufbuild/buf/cmd/buf lint
