# Copyright (c) Kasefuchs
# SPDX-License-Identifier: MPL-2.0

---
version: 3

tasks:
  add-license-headers:
    cmd: go run github.com/hashicorp/copywrite headers

  validate-license:
    cmd: go run github.com/hashicorp/copywrite license

  format-proto:
    cmd: go run github.com/bufbuild/buf/cmd/buf format -w api/proto/

  generate-proto:
    cmd: go run github.com/bufbuild/buf/cmd/buf generate

  format-go:
    cmd: go run mvdan.cc/gofumpt -l -w .
