# Copyright (c) Kasefuchs
# SPDX-License-Identifier: MPL-2.0

---
version: 3

tasks:
  license-headers:
    cmd: go run github.com/hashicorp/copywrite headers

  proto-gen:
    cmd: go run github.com/bufbuild/buf/cmd/buf generate

  proto-lint:
    cmd: go run github.com/bufbuild/buf/cmd/buf lint

  go-fmt:
    cmd: go run mvdan.cc/gofumpt -l -w .
