# Copyright (c) Kasefuchs
# SPDX-License-Identifier: MPL-2.0

---
enable_reflection: true

listen_address: 127.0.0.1:8083

database:
  type: sqlite
  dsn: ./session.sqlite3

user_service_url: 127.0.0.1:8081
token_service_url: 127.0.0.1:8082
